# -*- coding: utf-8 -*-
"""Projeto - ChatBot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqvK_eghFheaXxdXKFdc3whwCfqRrZHQ
"""

import google.generativeai as genai
import os
!pip install google-generativeai -q

try:
    API_KEY = os.environ['GOOGLE_API_KEY']
    genai.configure(api_key=API_KEY)
    print("Chave API do Google configurada com sucesso usando Secrets.")
except KeyError:
    print("ERRO: Chave API do Google não encontrada nos Secrets do Colab ('GOOGLE_API_KEY').")
    print("Por favor, configure sua chave API no painel 'Secrets' (ícone 🔑) antes de rodar o chatbot.")
    sair = True
except Exception as e:
    print(f"ERRO inesperado ao configurar a API: {e}")
    sair = True

if 'sair' in locals() and sair:
    exit()

try:
    model = genai.GenerativeModel('gemini-2.5-flash-latest')
    print("Modelo Gemini 2.5 Flash carregado com sucesso.")
except Exception as e:
    print(f"ERRO ao carregar o modelo Gemini 2.5 Flash: {e}")
    print("Verifique se sua Chave API está correta e ativa e se o modelo está disponível para você.")
    exit()

current_phase = 'welcome'
sair = False
user_focus = None
chosen_scenario = None
user_scenario_description = {}
identified_skills = set()

welcome_message = """
Olá! Que bom te ver por aqui. Sou sua Navegadora de Carreiras e Maternidade.
Meu objetivo é te ajudar a descobrir, reconhecer e comunicar o valor imenso das
habilidades que você desenvolveu cuidando dos seus filhos.
A maternidade nos ensina muito sobre gerenciar o caos, negociar sem parar e
liderar pelo exemplo! Vamos juntas explorar como tudo isso se aplica à sua carreira?
"""

focus_options = """
Para começar, pensando na sua jornada de carreira e maternidade, o que você mais gostaria de focar hoje?
1. Identificar habilidades para incluir no seu currículo/LinkedIn.
2. Preparar uma resposta para uma entrevista sobre sua pausa ou conciliação.
3. Apenas reconhecer e valorizar o que você aprendeu.
4. Outro objetivo.
Por favor, digite o número da sua escolha (ou 'sair' para encerrar):
"""

scenario_options = """
Vamos pensar em situações desafiadoras ou complexas que você enfrentou (ou enfrenta) no dia a dia com seus filhos.
Escolha uma área que te pareça interessante para explorar agora:
1. Gerenciar múltiplas tarefas ou pessoas ao mesmo tempo.
2. Resolver um conflito ou uma crise inesperada.
3. Planejar e organizar algo com muitos detalhes (uma viagem, uma festa, uma rotina).
4. Ensinar ou explicar algo complexo de forma simples e paciente.
5. Adaptar-se rapidamente a uma mudança de planos ou emergência.
6. Motivar alguém (seu filho, parceiro/a, etc.) a fazer algo que não queria.
7. Outra situação que você queira descrever.

Por favor, digite o número da sua escolha (ou 'sair' para voltar ao foco):
"""

scenario_details = {
    '1': {
        'text': 'Gerenciar múltiplas tarefas ou pessoas ao mesmo tempo',
        'questions': [
            "Descreva a situação: Quais eram as diferentes 'tarefas' ou 'pessoas' que você estava conciliando? O que era o mais difícil?",
            "Como você decidiu o que fazer primeiro? Que 'ferramentas' ou 'estratégias' você usou para lidar com tudo ao mesmo tempo? (Ex: fez listas, pediu ajuda, priorizou, aceitou imperfeição?)",
            "Qual foi o 'resultado' dessa situação? O que você conseguiu completar ou alcançar? O que você aprendeu sobre si mesma nesse processo?"
        ]
    },
     '2': {
        'text': 'Resolver um conflito ou uma crise inesperada',
        'questions': [
            "Descreva a situação do conflito/crise: Quem estava envolvido? Qual era o motivo principal da disputa ou o que causou a crise?",
            "Como você abordou a situação? Que perguntas você fez para entender o lado de cada um ou a raiz do problema? O que você fez ou disse?",
            "Que solução vocês (ou você) encontraram? Qual foi o resultado da sua intervenção? O que você aprendeu sobre si nesse momento?"
        ]
    },
     '3': {
        'text': 'Planejar e organizar algo com muitos detalhes',
        'questions': [
            "Descreva o que você precisou planejar/organizar (ex: viagem, festa, rotina, mudança). Quais eram os principais desafios ou detalhes a considerar?",
            "Como você começou a planejar? Que passos você seguiu? Que ferramentas (mentais ou físicas) usou para organizar (ex: planilhas, notas, aplicativos)?",
            "Qual foi o resultado desse planejamento/organização? Tudo saiu como esperado? O que você faria diferente? Que habilidade de planejamento/organização você sente que usou mais?"
        ]
    },
    '4': {
        'text': 'Ensinar ou explicar algo complexo de forma simples e paciente',
        'questions': [
            "O que você precisou ensinar ou explicar? Para quem? Qual era a principal dificuldade para a outra pessoa entender?",
            "Como você abordou o ensino/explicação? Que linguagem usou? Deu exemplos práticos? Teve que repetir ou tentar de formas diferentes? Como lidou com a frustração ou falta de interesse da outra pessoa?",
            "A outra pessoa conseguiu entender ou aprender? Qual foi o resultado? O que você aprendeu sobre comunicação ou paciência nesse processo?"
        ]
    },
     '5': {
        'text': 'Adaptar-se rapidamente a uma mudança de planos ou emergência',
        'questions': [
            "Descreva a mudança de planos ou emergência que aconteceu inesperadamente. Qual era o plano original ou a situação 'normal'?",
            "Como você reagiu inicialmente? Que passos você tomou para se adaptar ou lidar com a emergência? Teve que pensar rápido?",
            "Qual foi o desfecho da situação? Você conseguiu resolver o problema ou ajustar os planos com sucesso? O que essa experiência te ensinou sobre sua capacidade de adaptação ou resolução rápida?"
        ]
    },
     '6': {
        'text': 'Motivar alguém (seu filho, parceiro/a, etc.) a fazer algo que não queria',
        'questions': [
            "Quem você precisou motivar e a fazer o quê? Por que essa pessoa estava relutante?",
            "Que abordagens você utilizou para convencer ou incentivar? Usou conversa, negociação, recompensa, explicou o 'porquê'? Como lidou com a resistência inicial?",
            "A pessoa acabou fazendo o que era necessário? Qual foi o resultado da sua tentativa de motivação? O que você aprendeu sobre persuasão ou influência nesse processo?"
        ]
    },
     '7': {
         'text': 'Outra situação que você queira descrever',
         'questions': [
             "Por favor, descreva brevemente a situação da maternidade que você quer explorar.",
             "Agora, pense em como você agiu nessa situação. Quais foram seus principais passos, decisões ou desafios?",
             "E qual foi o resultado? O que você conseguiu alcançar e o que essa experiência te ensinou?"
         ]
     }
}

skill_templates = {
    'Organização': "Demonstro forte capacidade de **{skill_name}** e coordenação, gerenciando [descrever brevemente o cenário/resultado].",
    'Planejamento Estratégico': "Habilidade comprovada em **{skill_name}** para antecipar necessidades e planejar [descrever brevemente o cenário/resultado].",
    'Gestão de Tarefas': "Eficaz em **{skill_name}**, organizando e acompanhando múltiplas responsabilidades para [descrever brevemente o cenário/resultado].",
    'Priorização': "Experiência em **{skill_name}**, focando recursos e esforços nas atividades mais críticas em [descrever brevemente o cenário/resultado].",
    'Resolução de Conflitos': "Proficiente em **{skill_name}** e mediação, facilitando acordos em [descrever brevemente o cenário/resultado].",
    'Negociação': "Forte poder de **{skill_name}**, alcançando resultados mutuamente benéficos em [descrever brevemente o cenário/resultado].",
    'Mediação': "Habilidade em **{skill_name}**, facilitando a comunicação e o entendimento entre partes em [descrever brevemente o cenário/resultado].",
    'Resiliência': "Alta **{skill_name}** e capacidade de manter a calma e o foco sob pressão em [descrever brevemente o cenário/resultado].",
    'Gerenciamento de Estresse': "Desenvolvi técnicas eficazes de **{skill_name}**, mantendo a produtividade e clareza em [descrever brevemente o cenário/resultado].",
    'Multitarefa': "Excelente **{skill_name}** e capacidade de gerenciar eficientemente múltiplos projetos e demandas simultaneamente em [descrever brevemente o cenário/resultado].",
    'Mentoria/Treinamento': "Experiência em **{skill_name}** em guiar e desenvolver indivíduos.",
    'Comunicação Clara': "Forte **{skill_name}**, simplificando informações complexas para diferentes públicos.",
    'Comunicação Eficaz': "Habilidade em **{skill_name}**, transmitindo mensagens de forma clara e impactante.",
    'Adaptabilidade': "Alta **{skill_name}**, ajustando planos e estratégias rapidamente em resposta a mudanças inesperadas.",
    'Gestão de Crises': "Capacidade comprovada em **{skill_name}**, atuando com calma e eficácia para resolver problemas urgentes.",
    'Tomada de Decisão Rápida': "Proficiente em **{skill_name}**, avaliando situações rapidamente para determinar o melhor curso de ação.",
    'Liderança/Influência': "Demonstro **{skill_name}** e capacidade de influenciar positivamente o comportamento para alcançar objetivos.",
    'Persuasão': "Habilidade em **{skill_name}**, utilizando comunicação eficaz para alinhar perspectivas e alcançar consensos.",
    'Gerenciamento': "Desenvolvi habilidades de **{skill_name}**, coordenando recursos e pessoas.",
    'Resolução de Problemas': "Forte aptidão para **{skill_name}**, identificando desafios e implementando soluções eficazes.",
    'Paciência': "Alta **{skill_name}** e persistência em lidar com processos longos ou desafiadores.",
    'Empatia': "Cultivei **{skill_name}** e compreensão, criando conexões e respondendo a necessidades emocionais."
}

def generate_professional_phrase(skill_name, scenario_text):
    template = skill_templates.get(skill_name, f"Desenvolvi habilidades de **{{skill_name}}** em contextos de alta demanda.")
    scenario_summary = scenario_text
    phrase = template.format(
        skill_name=skill_name,
        descrever=scenario_summary,
        cenário=scenario_summary
    )
    return phrase

def identify_skills_with_ai(scenario_description_text, ai_model):
    print("\nA Navegadora de Carreiras está pensando... (Consultando a IA para identificar habilidades)")
    prompt = f"""
A partir da seguinte descrição de uma experiência na maternidade, identifique as 3 a 7 habilidades profissionais mais relevantes que foram demonstradas.
Liste as habilidades identificadas como uma lista numerada no seguinte FORMATO (APENAS O NOME DA HABILIDADE):
1. Nome da Habilidade 1
2. Nome da Habilidade 2
3. Nome da Habilidade 3
...

Se a descrição não permitir identificar habilidades profissionais claras, responda apenas "Nenhuma habilidade identificada".

Descrição da Experiência:
"{scenario_description_text}"

Habilidades Identificadas:
"""
    identified_list = []
    try:
        response = ai_model.generate_content(prompt)
        ai_output = response.text
        print(f"(Resposta bruta da IA: {ai_output[:200]}...)")
        lines = ai_output.strip().split('\n')
        for line in lines:
            line = line.strip()
            if line and (line[0].isdigit() or line.startswith('-')):
                 parts = line.split('.', 1)
                 if len(parts) > 1:
                     skill_name = parts[1].strip()
                 else:
                     skill_name = line[1:].strip()
                 if skill_name and skill_name.lower() != "nenhuma habilidade identificada":
                     identified_list.append(skill_name)
        return set(identified_list)
    except Exception as e:
        print(f"Ocorreu um erro ao consultar a IA: {e}")
        print("Continuando sem a identificação de habilidades pela IA.")
        return set()

print(welcome_message)

while not sair:
    if current_phase == 'welcome':
        print(focus_options)
        user_input = input().strip().lower()

        if user_input == 'sair':
            sair = True
        elif user_input in ['1', '2', '3', '4']:
            user_focus = user_input
            if user_focus == '1': print("\nOk, vamos focar em identificar habilidades para currículo/LinkedIn!")
            elif user_focus == '2': print("\nCerto, vamos pensar em como articular isso em entrevistas!")
            elif user_focus == '3': print("\nPerfeito, vamos focar em reconhecer o seu valor!")
            elif user_focus == '4': print("\nEntendido, vamos descobrir habilidades e depois pensamos na aplicação.")
            current_phase = 'explore_scenarios'
        else:
            print("Desculpe, não entendi. Por favor, digite o número da sua escolha ou 'sair'.")

    elif current_phase == 'explore_scenarios':
        print("\n" + scenario_options)
        user_input = input().strip().lower()

        if user_input == 'sair':
            current_phase = 'next_steps'
        elif user_input in scenario_details:
            chosen_scenario = user_input
            print(f"\nÓtima escolha! Vamos explorar a situação de: {scenario_details[chosen_scenario]['text']}.")
            user_scenario_description = {}
            current_phase = 'probe_scenario'
            question_index = 0
            print(scenario_details[chosen_scenario]['questions'][question_index])
            user_scenario_description['current_question_index'] = question_index
        else:
            print("Desculpe, não entendi. Por favor, digite o número do cenário ou 'sair'.")

    elif current_phase == 'probe_scenario':
        user_input = input().strip()
        question_index = user_scenario_description.get('current_question_index', 0)

        user_scenario_description[f'q{question_index + 1}'] = user_input

        question_index += 1

        if question_index < len(scenario_details[chosen_scenario]['questions']):
            user_scenario_description['current_question_index'] = question_index
            print(scenario_details[chosen_scenario]['questions'][question_index])
        else:
            print("\nEntendido! Obrigada por compartilhar essa experiência em detalhes.")
            full_description = " ".join([user_scenario_description.get(f'q{i+1}', '') for i in range(len(scenario_details[chosen_scenario]['questions']))])
            user_scenario_description['full_description'] = full_description
            current_phase = 'identify_skills'

    elif current_phase == 'identify_skills':
        full_description = user_scenario_description.get('full_description', '')

        if full_description:
            identified_skills_names = identify_skills_with_ai(full_description, model)

            if identified_skills_names:
                identified_skills = set()
                print("\nCom base na sua experiência, a IA identificou as seguintes habilidades profissionais:")
                for skill_name in identified_skills_names:
                    print(f"- **{skill_name}**")
                    identified_skills.add(skill_name)

                print("\nPercebe como essas 'habilidades de mãe' são valiosas no mercado de trabalho?")
            else:
                print("\nNão foi possível identificar habilidades claras com a IA a partir da sua descrição. Sua experiência ainda é válida!")
                identified_skills = set()

        else:
             print("\nNão recebi uma descrição completa para analisar. Pulando a identificação de habilidades com IA.")
             identified_skills = set()


        current_phase = 'apply_skills'

    elif current_phase == 'apply_skills':
        scenario_text = scenario_details.get(chosen_scenario, {}).get('text', 'uma situação pessoal')

        if identified_skills:
            print("\nAgora, vamos pensar em como você pode comunicar essas habilidades em um contexto profissional:")
            print("Aqui estão algumas sugestões de frases que você pode adaptar para seu currículo ou LinkedIn:")

            for skill_name in identified_skills:
                 phrase = generate_professional_phrase(skill_name, scenario_text)
                 print(f"- {phrase}")

            if user_focus == '2':
                 print("\nPara entrevistas, prepare-se para contar a história completa da situação que você descreveu (Situação, Ação, Resultado), focando nas habilidades profissionais que você usou.")

            print("\nLembre-se, estas são sugestões. Adapte-as para soarem naturais para você!")
        else:
            print("\nComo não identificamos habilidades claras automaticamente, vamos tentar pensar juntas: Que habilidade você sente que mais usou nessa situação? (Ex: paciência, criatividade, organização?) Sua experiência ainda é um ponto forte!")

        current_phase = 'next_steps'

    elif current_phase == 'next_steps':
        print("\nVocê é incrível! Sua experiência como mãe te equipou com competências valiosas que são verdadeiros diferenciais na sua carreira.")

        print("\nO que você gostaria de fazer agora?")
        print("1. Explorar outra situação da maternidade.")
        print("2. Recomeçar e ajustar meu foco (currículo, entrevista, etc.).")
        print("3. Encerrar a conversa por hoje.")
        user_input = input().strip().lower()

        if user_input == '1':
            current_phase = 'explore_scenarios'
            identified_skills = set()
            user_scenario_description = {}
            chosen_scenario = None
        elif user_input == '2':
            current_phase = 'welcome'
            identified_skills = set()
            user_scenario_description = {}
            chosen_scenario = None
            user_focus = None
        elif user_input == '3' or user_input == 'sair':
            sair = True
        else:
            print("Desculpe, não entendi. Por favor, digite 1, 2 ou 3.")


if sair:
    print("\nFoi ótimo conversar com você! Lembre-se do seu valor e das suas habilidades. Quando precisar, a Navegadora de Carreiras e Maternidade estará aqui. 😊")